### ISSUE TITLE
Towards v1.0

### ISSUE THREAD

**Issue by iamhyc** [iamhyc/Overleaf-Workshop#3]
(v0.1) **Compile and PDF View**
> When: `stars >= 5` && `date <= 20230915`
- [ ] compile project: 1) on save, 2) on `ctrl+alt+b`
- [ ] display compile icon on status bar
- [ ] update output files in tree view
- [ ] display PDF file with `PDF.js` (`ctrl+alt+v`)
- [ ] support sync (jump) between TEX and PDF

(v0.2) **User Experience Enhancement (Phase I)**
  > When: `stars >= 10` && `date <= 20230930`
- [ ] support *invisible mode*: only use REST API
- [ ] support project create/archive/delete/rename
- [ ] support local spell check (via "vscode-spell-checker")
- [ ] support basic intellisense via `metadata`
- [ ] display compile error message

(v0.3) **Initial Collaboration Support**
  > When `stars >= 20` && `date <= 20231231`
- [ ] support instant file changes sync
- [ ] display connected users on sidebar
- [ ] display history updates on sidebar
- [ ] `clientTracking` related API integration

(v0.4) **User Experience Enhancement (Phase II)**
  > When `stars >=30` && `date <= 20231231`
- [ ] support local snippet macro
- [ ] support local grammar linting
- [ ] display/restore archived projects
- [ ] display/restore trashed projects
- [ ] display/restore trashed files

(v0.5) **Advance Collaboration Support**
  > When `stars >=50` && `date <= 20231231`
- [ ] display colored multi-user cursors (via `setDecorations`)
- [ ] send/receive chat message

(v1.0) **User Experience Enhancement (Phase III)**
  > When `stars >= 100` && `date <= 20231231`
- [ ] support project-specific settings:
       "Compiler", "Main document", "Spell check", "Dictionary", etc.
- [ ] support local git bridge

**Comment by iamhyc** [comment]
(v0.2) **User Experience Enhancement (Phase I)**
  > When: `stars >= 10` && `date <= 20230930`
- [ ] support project create/archive/delete/rename
- [ ] support local spell check (via `check`)
- [ ] support basic intellisense (via `metadata`)
- [ ] support local snippet macro
- [ ] display compile error message
- [ ] support *invisible mode*: only use REST API

(v0.3) **Initial Collaboration Support**
  > When: `stars >= 20` && `date <= 20231231`
- [ ] support robust file changes sync
- [ ] `clientTracking` related API integration
- [ ] display connected users on sidebar
- [ ] display history updates on sidebar
- [ ] support history label management
- [ ] support project label management
- [ ] support general webview-based login
  > e.g., "overleaf.com", SSO

(v0.4) **User Experience Enhancement (Phase II)**
  > When: `stars >=30` && `date <= 20231231`
- [ ] support local grammar linting
- [ ] display/restore archived projects
- [ ] display/restore trashed projects
- [ ] display/restore trashed files

(v0.5) **Advance Collaboration Support**
  > When: `stars >=50` && `date <= 20231231`
- [ ] display colored multi-user cursors (via `setDecorations`)
- [ ] display comment messages on sidebar
- [ ] send/receive chat message

(v1.0) **User Experience Enhancement (Phase III)**
  > When: `stars >= 100` && `date <= 20231231`
- [ ] support project-specific settings:
       "Compiler", "Main document", "Spell check", "Dictionary", etc.
- [ ] support local git bridge
- [ ] use webpack build to be used in `vscode.dev`
  > `socket.io-client` failed to bundle

**Comment by iamhyc** [comment]
(v0.3) **Initial Collaboration Support**
> Release Date: `20231004`
- [x] a5a97e5486c7c321e172d9af8086c2ef8f27cfde `clientTracking` related API integration
- [x] a5a97e5486c7c321e172d9af8086c2ef8f27cfde display connected users on status bar
- [x] 9416ac82c082e04fb09adf0511bffcf09bb06693 display colored multi-user cursors (via `setDecorations`)
- [x] 7ce700d8e9284b49144450b6b2e09adca30c2dd0 support project label management
- [x] display history updates on sidebar
  - 1e1e6a687b35301df62f230d7355228696cfa11d show diff for each file
  - 8589de0c31c98c3b8c8d16892de4bca781ff207f support history label management
- [x] 1bcc0e062936eb0b32cc1b0ad4ea0f5c90e54bf6 support robust file changes sync
  #16 
- [x] 716df46f5eb6cfdde10b2cf80c4cff0c2eaf50c9 support `socket.io` connecting to "overleaf.com"
- [x] e1bb1083f35e2acb854d0b9d941a17afd3fe4dc4 fix ascii character converting

**Comment by iamhyc** [comment]
(v0.4) **Chat Message Support**
- [x] #28 send/receive chat message on sidebar
- [x] #28 allow markdown rendering in chat message
- [x] #28 allow reply to previous message with thread-based rendering
- [x] #31 add context to text editor to copy selected text as range, `ctrl+shift+c`
- [x] #31 allow jump to text location in chat message, e.g., `src/main.tex#L12C12-L15C0`
- [x] #31 click username to add cite text to input box
- [x] #31 notify unread messages and scroll into view
- [x] #31 change status bar icon when got new messages

**Comment by iamhyc** [comment]
(v0.5) **Local Intellisense Enhance pt.1** & **Local Replica**
> Release Date: `20231128`
- [x] 8d2ace909e71bd5bdde97d14f48d71043696dff5 project settings: compiler/spell check switch
- [x] bc39e015f1713e459578ece0c8052bdd29faf128 project settings: spell check dictionary unlearn
- [x] #33 fix: command auto-complete
- [x] 53d85fd4734a026e97551da1bf6383eaf382523b support project upload
- [x] 3e5ebb238205b72790975d90b7168100a66a0079 support project download (at any version)
- [x] 79fb4945e407c1458cc825e4291e96cbfb75c0c8 support customized history diff (current/previous/other)
- [x] e60dbd6bcc05ac16a22a6205efa860608a53b393 SCM interface and API design
- [x] fdfb2decbfbfd98c523a7b43ca6c30b6a447b977 support open as local replica
  > ~~setup local copy; path completion when create; use vscode fs to monitor changes and sync; ignore files sync by embedded rules; configure ignore rules; correct sync without loop call~~
- [x] b2516e18faeca8c7e25af3253e3fea6070d35c13 fix: local replica path resolve under windows
- [x] bacd53ab58de77335efbe3f5a01a6971ce102b65 support scm sync status bar item (invisible when no ongoing activities)
- [x] 0cbf07aca4a92d9104cc0ccba272a46ab540db27 "open locally" does not work properly
  - should fix all the uri resolve issue marked with `FIXME`
  - should set a context value to initialize the corresponding `vfs` when open path matches
- [x] #40 fix: better re-connection

**Comment by iamhyc** [comment]
(v0.6) **Local Intellisense Enhance pt.2**
> Release Date: 20231218
- [x] dbf1e048c63e6efeec150ff0d96f7dc91b9294f9 feat: allow enable/disable SCM
- [x] 265fe3b2304d89b346b7aae5f7a4325ae5685942 fix: restore pdf viewer scroll position
- [x] 056c18f2df6af96abdfd6d5fcd7b7a3d43b2688f feat: local replica maintain base version for patched update from remote (instead of always overwriting)
- [x] #54 support symbol provider for file outline
- [x] #54 support code formatting (whole/partial/editing)

**Comment by iamhyc** [comment]
(v0.7) **Overleaf Invisible Mode**
> Release Date: `20231229`
- [x] Overleaf Invisible Mode: #39

**Comment by iamhyc** [comment]
(v0.8) **User/Developer Experience Enhancement**
> Release Date: `20240112`
- [x] issue template
- [x] update CHANGELOG
- [x] support l10n
- [x] configuration
  > ~~PDF viewer theme configuration; compile on save or not, output folder name; vfs/message refresh interval, inactive timeout~~
- [x] basic documentation: framework, FAQ, build/contribution guidance, etc.
- [x] enable `master` branch protection, and PR rule protection
- [x] GitHub Workflows
  - **package task**: triggered when PR created/edited, with `vsix` artifact generated;

**Comment by iamhyc** [comment]
**v0.16.0** Local Replica Enhancement
> Release Date: before `2025-01-30`

- local version tracking
- merge mechanism: force overwrite --> merge-and-update
